### ISSUE TITLE
Error running

### ISSUE THREAD

**Issue by juanibiapina** [davidhampgonsalves/slackline#1]
Love the idea, but doesn't work:

```
$ slackline --init
failed MSpanList_Insert 0x676000 0x183100c2233fe 0x0
fatal error: MSpanList_Insert

etc etc
```

**Comment by davidhampgonsalves** [comment]
I don't use this actively anymore but I did just install via `go get github.com/davidhampgonsalves/slackline` and it worked successfully.

**Comment by juanibiapina** [comment]
Maybe it's specific to brew install

**Comment by davidhampgonsalves** [comment]
Probably and I removed the brew method from the install options since the `go get` will age better. Thanks for reporting.
